from django.urls import path
from .views import(
    home, dashboard, 
    add_apartment, add_apartment,
    update_apartment, update_apartment,
    add_villa, add_villa, 
    update_villa, update_villa, 
    add_zamin, add_zamin,
    update_zamin, update_zamin,
    apartment_all, apartment_all,
    villa_all, villa_all,
    zamin_all, zamin_all,
    apartment_detail, mostaghelat_detail,
    villa_detail, bagh_detail,
    zamin_detail, khane_detail,
    maqaze_detail,
    add_maqaze, add_bagh, 
    add_khane, add_mostaqelat, 
    update_maqaze, update_bagh, 
    update_khane, update_mostaghelat, 
    bagh_all, khane_all, 
    mostaghelat_all, maqaze_all,
    archive_all, archive_detail, 
    add_archive,update_archive,
)


urlpatterns = [
    path('', home, name='home'),
    path('dashboard/', dashboard, name='dashboard'),
    # all
    path('apartment/all', apartment_all, name='apartment-all'),
    path('villa/all', villa_all, name='villa-all'),
    path('zamin/all', zamin_all, name='zamin-all'),
    path('khane/all', khane_all, name='khane-all'),
    path('mostaghelat/all', mostaghelat_all, name='mostaghelat-all'),
    path('maqaze/all', maqaze_all, name='maqaze-all'),
    path('bagh/all', bagh_all, name='bagh-all'),
    path('archive/all', archive_all, name='archive-all'),
    # add
    path('apartment/add', add_apartment, name='apartment-add'),
    path('villa/add', add_villa, name='villa-add'),
    path('zamin/add', add_zamin, name='zamin-add'),
    path('khane/add', add_khane, name='khane-add'),
    path('mostaghelat/add', add_mostaqelat, name='mostaghelat-add'),
    path('maqaze/add', add_maqaze, name='maqaze-add'),
    path('bagh/add', add_bagh, name='bagh-add'),
    path('archive/add', add_archive, name='archive-add'),
    # update
    path('apartment/update/<int:pk>', update_apartment, name='apartment-update'),
    path('villa/update/<int:pk>', update_villa, name='villa-update'),
    path('zamin/update/<int:pk>', update_zamin, name='zamin-update'),
    path('khane/update/<int:pk>', update_khane, name='khane-update'),
    path('mostaghelat/update/<int:pk>', update_mostaghelat, name='mostaghelat-update'),
    path('maqaze/update/<int:pk>', update_maqaze, name='maqaze-update'),
    path('bagh/update/<int:pk>', update_bagh, name='bagh-update'),
    path('archive/update/<int:pk>', update_archive, name='archive-update'),
    # detail 
    path('zamin/<int:pk>', zamin_detail, name='zamin-detail'),
    path('villa/<int:pk>', villa_detail, name='villa-detail'),
    path('apartment/<int:pk>', apartment_detail, name='apartment-detail'),
    path('khane/<int:pk>', khane_detail, name='khane-detail'),
    path('mostaghelat/<int:pk>', mostaghelat_detail, name='mostaghelat-detail'),
    path('maqaze/<int:pk>', maqaze_detail, name='maqaze-detail'),
    path('bagh/<int:pk>', bagh_detail, name='bagh-detail'),
    path('archive/<int:pk>', archive_detail, name='archive-detail'),
]
