# Generated by Django 4.1.2 on 2022-10-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amlak', '0002_apartmentbuy_image_apartmentsell_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentbuy',
            name='malek_mobile',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='apartmentsell',
            name='malek_mobile',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='villabuy',
            name='malek_mobile',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='villasell',
            name='malek_mobile',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='zaminbuy',
            name='malek_mobile',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='zaminsell',
            name='malek_mobile',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
