# Generated by Django 4.1.2 on 2022-10-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amlak', '0005_alter_apartmentbuy_area_alter_apartmentbuy_build_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentbuy',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apartmentsell',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='villabuy',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='villasell',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='zaminbuy',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='zaminsell',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
