# Generated by Django 4.1.2 on 2022-10-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amlak', '0006_apartmentbuy_title_apartmentsell_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentbuy',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='apartmentsell',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='villabuy',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='villasell',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zaminbuy',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zaminsell',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
