# Generated by Django 4.1.2 on 2022-10-28 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amlak', '0007_alter_apartmentbuy_price_alter_apartmentsell_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentbuy',
            name='status',
        ),
        migrations.RemoveField(
            model_name='apartmentsell',
            name='status',
        ),
        migrations.RemoveField(
            model_name='villabuy',
            name='status',
        ),
        migrations.RemoveField(
            model_name='villasell',
            name='status',
        ),
        migrations.RemoveField(
            model_name='zaminbuy',
            name='status',
        ),
        migrations.RemoveField(
            model_name='zaminsell',
            name='status',
        ),
    ]
