# Generated by Django 4.1.2 on 2022-10-28 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amlak', '0008_remove_apartmentbuy_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentbuy',
            name='image',
        ),
        migrations.RemoveField(
            model_name='villabuy',
            name='image',
        ),
        migrations.RemoveField(
            model_name='villasell',
            name='image',
        ),
        migrations.RemoveField(
            model_name='zaminbuy',
            name='image',
        ),
        migrations.RemoveField(
            model_name='zaminsell',
            name='image',
        ),
        migrations.CreateModel(
            name='ZaminSellImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='zamin-sell')),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('zamin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amlak.zaminsell')),
            ],
        ),
        migrations.CreateModel(
            name='ZaminBuyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='zamin-buy')),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('zamin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amlak.zaminbuy')),
            ],
        ),
        migrations.CreateModel(
            name='VillaSellImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='villa-sell')),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amlak.villasell')),
            ],
        ),
        migrations.CreateModel(
            name='VillaBuyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='villa-buy')),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amlak.villabuy')),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentSellImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='apartment-sell')),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amlak.apartmentsell')),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentBuyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='apartment-buy')),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amlak.apartmentbuy')),
            ],
        ),
    ]
