# Generated by Django 4.1.2 on 2022-10-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amlak', '0009_remove_apartmentbuy_image_remove_villabuy_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentbuy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='apartment-buy'),
        ),
        migrations.AddField(
            model_name='villabuy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='villa-buy'),
        ),
        migrations.AddField(
            model_name='villasell',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='villa-sell'),
        ),
        migrations.AddField(
            model_name='zaminbuy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='zamin-buy'),
        ),
        migrations.AddField(
            model_name='zaminsell',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='zamin-sell'),
        ),
    ]
