# Generated by Django 4.1.2 on 2022-10-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amlak', '0011_apartment_apartmentimage_bagh_khane_maqaze_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_malek', models.CharField(blank=True, max_length=100, null=True)),
                ('address_malek', models.TextField(null=True)),
                ('mobile_malek', models.CharField(blank=True, max_length=20, null=True)),
                ('necessary_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('needed_melk', models.CharField(choices=[('زمین', 'زمین'), ('باغ', 'باغ'), ('ویلا', 'ویلا'), ('آپارتمان', 'آپارتمان'), ('مستقلات', 'مستقلات'), ('خانه', 'خانه'), ('مغازه', 'مغازه')], max_length=50)),
                ('needed_area', models.CharField(blank=True, max_length=50, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('melk_karbari', models.CharField(blank=True, max_length=50, null=True)),
                ('bodge', models.CharField(blank=True, max_length=50, null=True)),
                ('need_kharidar', models.CharField(blank=True, max_length=100, null=True)),
                ('olaviat', models.CharField(blank=True, max_length=100, null=True)),
                ('ejra_paymankari', models.BooleanField(default=True)),
                ('khadamat', models.BooleanField(default=True)),
                ('tarahi_koli', models.BooleanField(default=True)),
                ('other', models.CharField(blank=True, max_length=100, null=True)),
                ('name_moshaver', models.CharField(blank=True, max_length=50, null=True)),
                ('suggest_moshaver', models.CharField(blank=True, max_length=100, null=True)),
                ('features_user', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
