# Generated by Django 4.1.2 on 2022-10-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amlak', '0012_archiveuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villaimage',
            name='villa',
        ),
        migrations.RemoveField(
            model_name='zaminimage',
            name='zamin',
        ),
        migrations.RenameField(
            model_name='zamin',
            old_name='image',
            new_name='image_1',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='image',
        ),
        migrations.RemoveField(
            model_name='bagh',
            name='image',
        ),
        migrations.RemoveField(
            model_name='khane',
            name='image',
        ),
        migrations.RemoveField(
            model_name='maqaze',
            name='image',
        ),
        migrations.RemoveField(
            model_name='mostaghelat',
            name='image',
        ),
        migrations.RemoveField(
            model_name='villa',
            name='image',
        ),
        migrations.AddField(
            model_name='apartment',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='apartment'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='image_10',
            field=models.ImageField(blank=True, null=True, upload_to='apartment'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='apartment'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='apartment'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='apartment'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='apartment'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='image_6',
            field=models.ImageField(blank=True, null=True, upload_to='apartment'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='image_7',
            field=models.ImageField(blank=True, null=True, upload_to='apartment'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='image_8',
            field=models.ImageField(blank=True, null=True, upload_to='apartment'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='image_9',
            field=models.ImageField(blank=True, null=True, upload_to='apartment'),
        ),
        migrations.AddField(
            model_name='bagh',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='baqh'),
        ),
        migrations.AddField(
            model_name='bagh',
            name='image_10',
            field=models.ImageField(blank=True, null=True, upload_to='baqh'),
        ),
        migrations.AddField(
            model_name='bagh',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='baqh'),
        ),
        migrations.AddField(
            model_name='bagh',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='baqh'),
        ),
        migrations.AddField(
            model_name='bagh',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='baqh'),
        ),
        migrations.AddField(
            model_name='bagh',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='baqh'),
        ),
        migrations.AddField(
            model_name='bagh',
            name='image_6',
            field=models.ImageField(blank=True, null=True, upload_to='baqh'),
        ),
        migrations.AddField(
            model_name='bagh',
            name='image_7',
            field=models.ImageField(blank=True, null=True, upload_to='baqh'),
        ),
        migrations.AddField(
            model_name='bagh',
            name='image_8',
            field=models.ImageField(blank=True, null=True, upload_to='baqh'),
        ),
        migrations.AddField(
            model_name='bagh',
            name='image_9',
            field=models.ImageField(blank=True, null=True, upload_to='baqh'),
        ),
        migrations.AddField(
            model_name='khane',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='khane'),
        ),
        migrations.AddField(
            model_name='khane',
            name='image_10',
            field=models.ImageField(blank=True, null=True, upload_to='khane'),
        ),
        migrations.AddField(
            model_name='khane',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='khane'),
        ),
        migrations.AddField(
            model_name='khane',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='khane'),
        ),
        migrations.AddField(
            model_name='khane',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='khane'),
        ),
        migrations.AddField(
            model_name='khane',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='khane'),
        ),
        migrations.AddField(
            model_name='khane',
            name='image_6',
            field=models.ImageField(blank=True, null=True, upload_to='khane'),
        ),
        migrations.AddField(
            model_name='khane',
            name='image_7',
            field=models.ImageField(blank=True, null=True, upload_to='khane'),
        ),
        migrations.AddField(
            model_name='khane',
            name='image_8',
            field=models.ImageField(blank=True, null=True, upload_to='khane'),
        ),
        migrations.AddField(
            model_name='khane',
            name='image_9',
            field=models.ImageField(blank=True, null=True, upload_to='khane'),
        ),
        migrations.AddField(
            model_name='maqaze',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='maqaze'),
        ),
        migrations.AddField(
            model_name='maqaze',
            name='image_10',
            field=models.ImageField(blank=True, null=True, upload_to='maqaze'),
        ),
        migrations.AddField(
            model_name='maqaze',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='maqaze'),
        ),
        migrations.AddField(
            model_name='maqaze',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='maqaze'),
        ),
        migrations.AddField(
            model_name='maqaze',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='maqaze'),
        ),
        migrations.AddField(
            model_name='maqaze',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='maqaze'),
        ),
        migrations.AddField(
            model_name='maqaze',
            name='image_6',
            field=models.ImageField(blank=True, null=True, upload_to='maqaze'),
        ),
        migrations.AddField(
            model_name='maqaze',
            name='image_7',
            field=models.ImageField(blank=True, null=True, upload_to='maqaze'),
        ),
        migrations.AddField(
            model_name='maqaze',
            name='image_8',
            field=models.ImageField(blank=True, null=True, upload_to='maqaze'),
        ),
        migrations.AddField(
            model_name='maqaze',
            name='image_9',
            field=models.ImageField(blank=True, null=True, upload_to='maqaze'),
        ),
        migrations.AddField(
            model_name='mostaghelat',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='mostaqelat'),
        ),
        migrations.AddField(
            model_name='mostaghelat',
            name='image_10',
            field=models.ImageField(blank=True, null=True, upload_to='mostaqelat'),
        ),
        migrations.AddField(
            model_name='mostaghelat',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='mostaqelat'),
        ),
        migrations.AddField(
            model_name='mostaghelat',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='mostaqelat'),
        ),
        migrations.AddField(
            model_name='mostaghelat',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='mostaqelat'),
        ),
        migrations.AddField(
            model_name='mostaghelat',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='mostaqelat'),
        ),
        migrations.AddField(
            model_name='mostaghelat',
            name='image_6',
            field=models.ImageField(blank=True, null=True, upload_to='mostaqelat'),
        ),
        migrations.AddField(
            model_name='mostaghelat',
            name='image_7',
            field=models.ImageField(blank=True, null=True, upload_to='mostaqelat'),
        ),
        migrations.AddField(
            model_name='mostaghelat',
            name='image_8',
            field=models.ImageField(blank=True, null=True, upload_to='mostaqelat'),
        ),
        migrations.AddField(
            model_name='mostaghelat',
            name='image_9',
            field=models.ImageField(blank=True, null=True, upload_to='mostaqelat'),
        ),
        migrations.AddField(
            model_name='villa',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='villa'),
        ),
        migrations.AddField(
            model_name='villa',
            name='image_10',
            field=models.ImageField(blank=True, null=True, upload_to='villa'),
        ),
        migrations.AddField(
            model_name='villa',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='villa'),
        ),
        migrations.AddField(
            model_name='villa',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='villa'),
        ),
        migrations.AddField(
            model_name='villa',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='villa'),
        ),
        migrations.AddField(
            model_name='villa',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='villa'),
        ),
        migrations.AddField(
            model_name='villa',
            name='image_6',
            field=models.ImageField(blank=True, null=True, upload_to='villa'),
        ),
        migrations.AddField(
            model_name='villa',
            name='image_7',
            field=models.ImageField(blank=True, null=True, upload_to='villa'),
        ),
        migrations.AddField(
            model_name='villa',
            name='image_8',
            field=models.ImageField(blank=True, null=True, upload_to='villa'),
        ),
        migrations.AddField(
            model_name='villa',
            name='image_9',
            field=models.ImageField(blank=True, null=True, upload_to='villa'),
        ),
        migrations.AddField(
            model_name='zamin',
            name='image_10',
            field=models.ImageField(blank=True, null=True, upload_to='zamin'),
        ),
        migrations.AddField(
            model_name='zamin',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='zamin'),
        ),
        migrations.AddField(
            model_name='zamin',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='zamin'),
        ),
        migrations.AddField(
            model_name='zamin',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='zamin'),
        ),
        migrations.AddField(
            model_name='zamin',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='zamin'),
        ),
        migrations.AddField(
            model_name='zamin',
            name='image_6',
            field=models.ImageField(blank=True, null=True, upload_to='zamin'),
        ),
        migrations.AddField(
            model_name='zamin',
            name='image_7',
            field=models.ImageField(blank=True, null=True, upload_to='zamin'),
        ),
        migrations.AddField(
            model_name='zamin',
            name='image_8',
            field=models.ImageField(blank=True, null=True, upload_to='zamin'),
        ),
        migrations.AddField(
            model_name='zamin',
            name='image_9',
            field=models.ImageField(blank=True, null=True, upload_to='zamin'),
        ),
        migrations.DeleteModel(
            name='ApartmentImage',
        ),
        migrations.DeleteModel(
            name='VillaImage',
        ),
        migrations.DeleteModel(
            name='ZaminImage',
        ),
    ]
