# Generated by Django 4.1.2 on 2022-10-30 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amlak', '0013_remove_villaimage_villa_remove_zaminimage_zamin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='malek_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام مالک'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='malek_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام مالک'),
        ),
    ]
