# Generated by Django 4.1.2 on 2022-10-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amlak', '0014_alter_apartment_malek_name_alter_khane_malek_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archiveuser',
            name='need_kharidar',
        ),
        migrations.RemoveField(
            model_name='mostaghelat',
            name='fitures',
        ),
        migrations.RemoveField(
            model_name='mostaghelat',
            name='mojtama_apartment',
        ),
        migrations.AlterField(
            model_name='apartment',
            name='address',
            field=models.TextField(null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مساحت'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='area_building',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='متراژ بنا'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='asansor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='آسانسور'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='baft',
            field=models.CharField(choices=[('شهری', 'شهری'), ('روستایی', 'روستایی'), ('خارج بافت', 'خارج بافت'), ('قسمتی در بافت', 'قسمتی در بافت'), ('قابلیت الحاق به بافت', 'قابلیت الحاق به بافت')], max_length=50, verbose_name='بافت'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='bam',
            field=models.CharField(choices=[('اسپانش', 'اسپانش'), ('شیروانی', 'شیروانی'), ('مسطح سنتی', 'مسطح سنتی')], max_length=50, verbose_name='بام'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='bar_zamin',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='بر زمین'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='build_age',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='سال ساخت'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='dastrsi',
            field=models.CharField(choices=[('آسفالت', 'آسفالت'), ('خاکی', 'خاکی'), ('خاکی قدیمی', 'خاکی قدیمی'), ('عدم دسترسی', 'عدم دسترسی'), ('سایر موارد', 'سایر موارد')], max_length=50, verbose_name='دسترسی'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='description',
            field=models.TextField(null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='edit',
            field=models.CharField(choices=[('دارد', 'دارد'), ('ندارد', 'ندارد')], max_length=50, verbose_name='وضعیت اصلاحی'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='features',
            field=models.CharField(choices=[('مشجر', 'مشجر'), ('درخشان مشجر', 'درخشان مشجر'), ('فضا سازی شده', 'فضا سازی شده'), ('فاقد ویژگی خاص', 'فاقد ویژگی خاص')], max_length=50, verbose_name='ویژگی ها'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='fitures',
            field=models.CharField(choices=[('سونا', 'سونا'), ('استخر سرپوشیده', 'استخر سر پوشیده'), ('استخر باز', 'استخر باز')], max_length=50, verbose_name='ویژگی ها'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='floor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='طبقه'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='floor_count',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='تعداد طبقات'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='garmayesh',
            field=models.CharField(choices=[('بخاری', 'بخاری'), ('موتور خانه', 'موتور خانه'), ('فن گویل', 'فن کوِیل'), ('چیلر', 'چیلر')], max_length=50, verbose_name='گرمایش'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='gozar',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='گذر'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='image_10',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='image_6',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='image_7',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='image_8',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='image_9',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='javaz',
            field=models.CharField(choices=[('دارد', 'دارد'), ('ندارد', 'ندارد'), ('مراحل اداری اخذ جواز', 'مراحل اداری اخذ جواز')], max_length=50, verbose_name='جواز'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='javaz_villa',
            field=models.CharField(choices=[('نقشه؟', 'نقشه؟'), ('عدم', 'عدم'), ('پایان کار', 'پایان کار')], max_length=50, verbose_name='جواز ویلا'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='kaf',
            field=models.CharField(choices=[('سنگ', 'سنگ'), ('سرامیک', 'سرامیک'), ('سایر', 'سایر')], max_length=50, verbose_name='کف'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='karbari',
            field=models.CharField(choices=[('مسکونی', 'مسکونی'), ('صنعتی', 'صنعتی'), ('تجاری', 'تجاری'), ('کشاورزی', 'کشاورزی'), ('اداری', 'اداری'), ('سایر', 'سایر')], max_length=50, verbose_name='کاربری'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='kichen',
            field=models.CharField(choices=[('اپن', 'اپن'), ('زیر اپن', 'زیر اپن'), ('کلوز', 'کلوز')], max_length=50, verbose_name='آشپزخانه'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='malek_address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس مالک'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='malek_mobile',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='تلفن مالک'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='malek_need',
            field=models.CharField(choices=[('فروش', 'فروش'), ('تهاتر', 'تهاتر'), ('مشارکت', 'مشارکت'), ('معاوضه', 'معاوضه')], max_length=50, verbose_name='نیاز مالک'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='mechanic_biulding',
            field=models.CharField(choices=[('ستون ها', 'ستون ها'), ('رازر ها', 'رازر ها'), ('سایر', 'سایر')], max_length=50, verbose_name='مکانیک ساختمان'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='nama_building',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نمای ساختمان'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='necessary_mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن ضروری'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='parking',
            field=models.CharField(choices=[('مسقف', 'مسقف'), ('فضا باز', 'فضا باز'), ('ندارد', 'ندارد')], max_length=50, verbose_name='پارکینگ'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='position',
            field=models.CharField(choices=[('شمالی', 'شمالی'), ('شرقی', 'شرقی'), ('جنوبی', 'جنوبی'), ('غربی', 'غربی'), ('تودلی شمالی', 'تودلی شمالی'), ('تودلی شرقی', 'تودلی شرقی'), ('تودلی جنوبی', 'تودلی جنوبی'), ('تودلی غربی', 'تودلی غربی')], max_length=50, verbose_name='موقعیت'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='post_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='sanad',
            field=models.CharField(choices=[('سند تک برگ', 'سند تک برگ'), ('سند قدیمی', 'سند قدیمی'), ('سند شاعی', 'سند شاعی'), ('فاقد سند', 'فاقد سند')], max_length=50, verbose_name='سند'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='sarmayesh',
            field=models.CharField(choices=[('کولر آبی', 'کولر آبی'), ('کولر گازی', 'کولر گازی'), ('فن کویل', 'فن کویل')], max_length=50, verbose_name='سرمایش'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='system_garmayesh',
            field=models.CharField(choices=[('از کف', 'از کف'), ('بخاری', 'بخاری'), ('رادیاتور', 'رادیاتور'), ('شومینه', 'شومینه')], max_length=50, verbose_name='سیستم گرمایش'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='topography',
            field=models.CharField(choices=[('شیب دار', 'شیب دار'), ('تپه ماهور', 'تپه ماهور'), ('مسطح', 'مسطح')], max_length=50, verbose_name='توپوگرافی'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='type_building',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع ساخت'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='vahed',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='واحد'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='vahed_count',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='تعداد واحد'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='view',
            field=models.CharField(choices=[('عالی', 'عالی'), ('خوب', 'خوب'), ('متوسط', 'متوسط'), ('بد', 'بد')], max_length=50, verbose_name='چشم انداز'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='zelzele',
            field=models.CharField(choices=[('عالی', 'عالی'), ('خوب', 'خوب'), ('متوسط', 'متوسط'), ('بد', 'بد')], max_length=50, verbose_name='طراحی ضد زلزله'),
        ),
        migrations.AlterField(
            model_name='archiveuser',
            name='address_malek',
            field=models.TextField(null=True, verbose_name='آدرس مالک'),
        ),
        migrations.AlterField(
            model_name='archiveuser',
            name='bodge',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='بودجه'),
        ),
        migrations.AlterField(
            model_name='archiveuser',
            name='ejra_paymankari',
            field=models.BooleanField(default=True, verbose_name='اجرای پیمانکاری'),
        ),
        migrations.AlterField(
            model_name='archiveuser',
            name='features_user',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='خصوصیات شخصی'),
        ),
        migrations.AlterField(
            model_name='archiveuser',
            name='khadamat',
            field=models.BooleanField(default=True, verbose_name='خدمات'),
        ),
        migrations.AlterField(
            model_name='archiveuser',
            name='melk_karbari',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کاربری'),
        ),
        migrations.AlterField(
            model_name='archiveuser',
            name='mobile_malek',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن مالک'),
        ),
        migrations.AlterField(
            model_name='archiveuser',
            name='name_malek',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام مالک'),
        ),
        migrations.AlterField(
            model_name='archiveuser',
            name='name_moshaver',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام مشاور'),
        ),
        migrations.AlterField(
            model_name='archiveuser',
            name='necessary_mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن ضروری'),
        ),
        migrations.AlterField(
            model_name='archiveuser',
            name='needed_area',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='مساحت'),
        ),
        migrations.AlterField(
            model_name='archiveuser',
            name='needed_melk',
            field=models.CharField(choices=[('زمین', 'زمین'), ('باغ', 'باغ'), ('ویلا', 'ویلا'), ('آپارتمان', 'آپارتمان'), ('مستقلات', 'مستقلات'), ('خانه', 'خانه'), ('مغازه', 'مغازه')], max_length=50, verbose_name='نوع ملک'),
        ),
        migrations.AlterField(
            model_name='archiveuser',
            name='olaviat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اولویت'),
        ),
        migrations.AlterField(
            model_name='archiveuser',
            name='other',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='سایر موارد'),
        ),
        migrations.AlterField(
            model_name='archiveuser',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='موقعیت'),
        ),
        migrations.AlterField(
            model_name='archiveuser',
            name='suggest_moshaver',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='پیشنهاد مشاور'),
        ),
        migrations.AlterField(
            model_name='archiveuser',
            name='tarahi_koli',
            field=models.BooleanField(default=True, verbose_name='طراحی کلی'),
        ),
        migrations.AlterField(
            model_name='bagh',
            name='address',
            field=models.TextField(null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='bagh',
            name='area',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مساحت'),
        ),
        migrations.AlterField(
            model_name='bagh',
            name='baft',
            field=models.CharField(choices=[('شهری', 'شهری'), ('روستایی', 'روستایی'), ('خارج بافت', 'خارج بافت'), ('قسمتی در بافت', 'قسمتی در بافت'), ('قابلیت الحاق به بافت', 'قابلیت الحاق به بافت')], max_length=50, verbose_name='بافت'),
        ),
        migrations.AlterField(
            model_name='bagh',
            name='bar_zamin',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='بر زمین'),
        ),
        migrations.AlterField(
            model_name='bagh',
            name='dastrsi',
            field=models.CharField(choices=[('آسفالت', 'آسفالت'), ('خاکی', 'خاکی'), ('خاکی قدیمی', 'خاکی قدیمی'), ('عدم دسترسی', 'عدم دسترسی'), ('سایر موارد', 'سایر موارد')], max_length=50, verbose_name='دسترسی'),
        ),
        migrations.AlterField(
            model_name='bagh',
            name='description',
            field=models.TextField(null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='bagh',
            name='edit',
            field=models.CharField(choices=[('دارد', 'دارد'), ('ندارد', 'ندارد')], max_length=50, verbose_name='وضعیت اصلاحی'),
        ),
        migrations.AlterField(
            model_name='bagh',
            name='features',
            field=models.CharField(choices=[('مشجر', 'مشجر'), ('درخشان مشجر', 'درخشان مشجر'), ('فضا سازی شده', 'فضا سازی شده'), ('فاقد ویژگی خاص', 'فاقد ویژگی خاص')], max_length=50, verbose_name='ویژگی ها'),
        ),
        migrations.AlterField(
            model_name='bagh',
            name='gozar',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='گذر'),
        ),
        migrations.AlterField(
            model_name='bagh',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='bagh',
            name='image_10',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='bagh',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='bagh',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='bagh',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='bagh',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='bagh',
            name='image_6',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='bagh',
            name='image_7',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='bagh',
            name='image_8',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='bagh',
            name='image_9',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='bagh',
            name='javaz',
            field=models.CharField(choices=[('دارد', 'دارد'), ('ندارد', 'ندارد'), ('مراحل اداری اخذ جواز', 'مراحل اداری اخذ جواز')], max_length=50, verbose_name='جواز'),
        ),
        migrations.AlterField(
            model_name='bagh',
            name='karbari',
            field=models.CharField(choices=[('مسکونی', 'مسکونی'), ('صنعتی', 'صنعتی'), ('تجاری', 'تجاری'), ('کشاورزی', 'کشاورزی'), ('اداری', 'اداری'), ('سایر', 'سایر')], max_length=50, verbose_name='کاربری'),
        ),
        migrations.AlterField(
            model_name='bagh',
            name='malek_address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس مالک'),
        ),
        migrations.AlterField(
            model_name='bagh',
            name='malek_mobile',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='تلفن مالک'),
        ),
        migrations.AlterField(
            model_name='bagh',
            name='malek_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام مالک'),
        ),
        migrations.AlterField(
            model_name='bagh',
            name='malek_need',
            field=models.CharField(choices=[('فروش', 'فروش'), ('تهاتر', 'تهاتر'), ('مشارکت', 'مشارکت'), ('معاوضه', 'معاوضه')], max_length=50, verbose_name='نیاز مالک'),
        ),
        migrations.AlterField(
            model_name='bagh',
            name='necessary_mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن ضروری'),
        ),
        migrations.AlterField(
            model_name='bagh',
            name='position',
            field=models.CharField(choices=[('شمالی', 'شمالی'), ('شرقی', 'شرقی'), ('جنوبی', 'جنوبی'), ('غربی', 'غربی'), ('تودلی شمالی', 'تودلی شمالی'), ('تودلی شرقی', 'تودلی شرقی'), ('تودلی جنوبی', 'تودلی جنوبی'), ('تودلی غربی', 'تودلی غربی')], max_length=50, verbose_name='موقعیت'),
        ),
        migrations.AlterField(
            model_name='bagh',
            name='post_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='bagh',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='bagh',
            name='sanad',
            field=models.CharField(choices=[('سند تک برگ', 'سند تک برگ'), ('سند قدیمی', 'سند قدیمی'), ('سند شاعی', 'سند شاعی'), ('فاقد سند', 'فاقد سند')], max_length=50, verbose_name='سند'),
        ),
        migrations.AlterField(
            model_name='bagh',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='bagh',
            name='topography',
            field=models.CharField(choices=[('شیب دار', 'شیب دار'), ('تپه ماهور', 'تپه ماهور'), ('مسطح', 'مسطح')], max_length=50, verbose_name='توپوگرافی'),
        ),
        migrations.AlterField(
            model_name='bagh',
            name='view',
            field=models.CharField(choices=[('عالی', 'عالی'), ('خوب', 'خوب'), ('متوسط', 'متوسط'), ('بد', 'بد')], max_length=50, verbose_name='چشم انداز'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='address',
            field=models.TextField(null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مساحت'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='area_building',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='متراژ'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='baft',
            field=models.CharField(choices=[('شهری', 'شهری'), ('روستایی', 'روستایی'), ('خارج بافت', 'خارج بافت'), ('قسمتی در بافت', 'قسمتی در بافت'), ('قابلیت الحاق به بافت', 'قابلیت الحاق به بافت')], max_length=50, verbose_name='بافت'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='bam',
            field=models.CharField(choices=[('اسپانش', 'اسپانش'), ('شیروانی', 'شیروانی'), ('مسطح سنتی', 'مسطح سنتی')], max_length=50, verbose_name='بام'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='bar_zamin',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='بر زمین'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='build_age',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='سال ساخت'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='dastrsi',
            field=models.CharField(choices=[('آسفالت', 'آسفالت'), ('خاکی', 'خاکی'), ('خاکی قدیمی', 'خاکی قدیمی'), ('عدم دسترسی', 'عدم دسترسی'), ('سایر موارد', 'سایر موارد')], max_length=50, verbose_name='دسترسی'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='description',
            field=models.TextField(null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='edit',
            field=models.CharField(choices=[('دارد', 'دارد'), ('ندارد', 'ندارد')], max_length=50, verbose_name='وضعیت اصلاحی'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='features',
            field=models.CharField(choices=[('مشجر', 'مشجر'), ('درخشان مشجر', 'درخشان مشجر'), ('فضا سازی شده', 'فضا سازی شده'), ('فاقد ویژگی خاص', 'فاقد ویژگی خاص')], max_length=50, verbose_name='ویژگی ها'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='fitures',
            field=models.CharField(choices=[('سونا', 'سونا'), ('استخر سرپوشیده', 'استخر سر پوشیده'), ('استخر باز', 'استخر باز')], max_length=50, verbose_name='سایر ویژگی های خاص'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='floor_count',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='تعدا طبقات'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='garmayesh',
            field=models.CharField(choices=[('بخاری', 'بخاری'), ('موتور خانه', 'موتور خانه'), ('فن گویل', 'فن کوِیل'), ('چیلر', 'چیلر')], max_length=50, verbose_name='گرمایش'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='gozar',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='گذر'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='image_10',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='image_6',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='image_7',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='image_8',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='image_9',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='javaz',
            field=models.CharField(choices=[('دارد', 'دارد'), ('ندارد', 'ندارد'), ('مراحل اداری اخذ جواز', 'مراحل اداری اخذ جواز')], max_length=50, verbose_name='جواز'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='javaz_villa',
            field=models.CharField(choices=[('نقشه؟', 'نقشه؟'), ('عدم', 'عدم'), ('پایان کار', 'پایان کار')], max_length=50, verbose_name='وضعیت جواز'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='kaf',
            field=models.CharField(choices=[('سنگ', 'سنگ'), ('سرامیک', 'سرامیک'), ('سایر', 'سایر')], max_length=50, verbose_name='کف'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='karbari',
            field=models.CharField(choices=[('مسکونی', 'مسکونی'), ('صنعتی', 'صنعتی'), ('تجاری', 'تجاری'), ('کشاورزی', 'کشاورزی'), ('اداری', 'اداری'), ('سایر', 'سایر')], max_length=50, verbose_name='کاربری'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='kichen',
            field=models.CharField(choices=[('اپن', 'اپن'), ('زیر اپن', 'زیر اپن'), ('کلوز', 'کلوز')], max_length=50, verbose_name='آشپزخانه'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='malek_address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس مالک'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='malek_mobile',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='تلفن مالک'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='malek_need',
            field=models.CharField(choices=[('فروش', 'فروش'), ('تهاتر', 'تهاتر'), ('مشارکت', 'مشارکت'), ('معاوضه', 'معاوضه')], max_length=50, verbose_name='نیاز مالک'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='mechanic_biulding',
            field=models.CharField(choices=[('ستون ها', 'ستون ها'), ('رازر ها', 'رازر ها'), ('سایر', 'سایر')], max_length=50, verbose_name='مکانیک ساختمان'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='nama_building',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نمای ساختمان'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='necessary_mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن ضروری'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='parking',
            field=models.CharField(choices=[('مسقف', 'مسقف'), ('فضا باز', 'فضا باز'), ('ندارد', 'ندارد')], max_length=50, verbose_name='پارکینگ'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='position',
            field=models.CharField(choices=[('شمالی', 'شمالی'), ('شرقی', 'شرقی'), ('جنوبی', 'جنوبی'), ('غربی', 'غربی'), ('تودلی شمالی', 'تودلی شمالی'), ('تودلی شرقی', 'تودلی شرقی'), ('تودلی جنوبی', 'تودلی جنوبی'), ('تودلی غربی', 'تودلی غربی')], max_length=50, verbose_name='موقعیت'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='post_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='sanad',
            field=models.CharField(choices=[('سند تک برگ', 'سند تک برگ'), ('سند قدیمی', 'سند قدیمی'), ('سند شاعی', 'سند شاعی'), ('فاقد سند', 'فاقد سند')], max_length=50, verbose_name='سند'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='sarmayesh',
            field=models.CharField(choices=[('کولر آبی', 'کولر آبی'), ('کولر گازی', 'کولر گازی'), ('فن کویل', 'فن کویل')], max_length=50, verbose_name='سرمایش'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='sokonat',
            field=models.CharField(choices=[('دارد', 'دارد'), ('ندارد', 'ندارد')], max_length=50, verbose_name='سکونت'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='system_garmayesh',
            field=models.CharField(choices=[('از کف', 'از کف'), ('بخاری', 'بخاری'), ('رادیاتور', 'رادیاتور'), ('شومینه', 'شومینه')], max_length=50, verbose_name='سیستم گرمایش'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='topography',
            field=models.CharField(choices=[('شیب دار', 'شیب دار'), ('تپه ماهور', 'تپه ماهور'), ('مسطح', 'مسطح')], max_length=50, verbose_name='توپوگرافی'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='type_building',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع ساخت'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='view',
            field=models.CharField(choices=[('عالی', 'عالی'), ('خوب', 'خوب'), ('متوسط', 'متوسط'), ('بد', 'بد')], max_length=50, verbose_name='چشم انداز'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='zelzele',
            field=models.CharField(choices=[('عالی', 'عالی'), ('خوب', 'خوب'), ('متوسط', 'متوسط'), ('بد', 'بد')], max_length=50, verbose_name='طراحی ضد زلزله'),
        ),
        migrations.AlterField(
            model_name='maqaze',
            name='address',
            field=models.TextField(null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='maqaze',
            name='area',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مساحت'),
        ),
        migrations.AlterField(
            model_name='maqaze',
            name='baft',
            field=models.CharField(choices=[('شهری', 'شهری'), ('روستایی', 'روستایی'), ('خارج بافت', 'خارج بافت'), ('قسمتی در بافت', 'قسمتی در بافت'), ('قابلیت الحاق به بافت', 'قابلیت الحاق به بافت')], max_length=50, verbose_name='بافت'),
        ),
        migrations.AlterField(
            model_name='maqaze',
            name='bar_zamin',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='بر زمین'),
        ),
        migrations.AlterField(
            model_name='maqaze',
            name='dastrsi',
            field=models.CharField(choices=[('آسفالت', 'آسفالت'), ('خاکی', 'خاکی'), ('خاکی قدیمی', 'خاکی قدیمی'), ('عدم دسترسی', 'عدم دسترسی'), ('سایر موارد', 'سایر موارد')], max_length=50, verbose_name='دسترسی'),
        ),
        migrations.AlterField(
            model_name='maqaze',
            name='description',
            field=models.TextField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='maqaze',
            name='edit',
            field=models.CharField(choices=[('دارد', 'دارد'), ('ندارد', 'ندارد')], max_length=50, verbose_name='وضعیت اصلاحی'),
        ),
        migrations.AlterField(
            model_name='maqaze',
            name='features',
            field=models.CharField(choices=[('مشجر', 'مشجر'), ('درخشان مشجر', 'درخشان مشجر'), ('فضا سازی شده', 'فضا سازی شده'), ('فاقد ویژگی خاص', 'فاقد ویژگی خاص')], max_length=50, verbose_name='ویژگی ها'),
        ),
        migrations.AlterField(
            model_name='maqaze',
            name='gozar',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='گذر'),
        ),
        migrations.AlterField(
            model_name='maqaze',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='maqaze',
            name='image_10',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='maqaze',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='maqaze',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='maqaze',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='maqaze',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='maqaze',
            name='image_6',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='maqaze',
            name='image_7',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='maqaze',
            name='image_8',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='maqaze',
            name='image_9',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='maqaze',
            name='javaz',
            field=models.CharField(choices=[('دارد', 'دارد'), ('ندارد', 'ندارد'), ('مراحل اداری اخذ جواز', 'مراحل اداری اخذ جواز')], max_length=50, verbose_name='جواز'),
        ),
        migrations.AlterField(
            model_name='maqaze',
            name='karbari',
            field=models.CharField(choices=[('مسکونی', 'مسکونی'), ('صنعتی', 'صنعتی'), ('تجاری', 'تجاری'), ('کشاورزی', 'کشاورزی'), ('اداری', 'اداری'), ('سایر', 'سایر')], max_length=50, verbose_name='کاربری'),
        ),
        migrations.AlterField(
            model_name='maqaze',
            name='karbari_khas',
            field=models.CharField(choices=[('کارگاهی', 'کارگاهی'), ('تجاری', 'تجاری'), ('موقعیت تجاری', 'موقعیت تجاری'), ('سایر موارد', 'سایر موارد')], max_length=50, verbose_name='کاربری خاص'),
        ),
        migrations.AlterField(
            model_name='maqaze',
            name='malek_address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس مالک'),
        ),
        migrations.AlterField(
            model_name='maqaze',
            name='malek_mobile',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='تلفن مالک'),
        ),
        migrations.AlterField(
            model_name='maqaze',
            name='malek_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام مالک'),
        ),
        migrations.AlterField(
            model_name='maqaze',
            name='malek_need',
            field=models.CharField(choices=[('فروش', 'فروش'), ('تهاتر', 'تهاتر'), ('مشارکت', 'مشارکت'), ('معاوضه', 'معاوضه')], max_length=50, verbose_name='نیاز مالک'),
        ),
        migrations.AlterField(
            model_name='maqaze',
            name='malekiat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مالکیت'),
        ),
        migrations.AlterField(
            model_name='maqaze',
            name='necessary_mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن ضروری'),
        ),
        migrations.AlterField(
            model_name='maqaze',
            name='position',
            field=models.CharField(choices=[('شمالی', 'شمالی'), ('شرقی', 'شرقی'), ('جنوبی', 'جنوبی'), ('غربی', 'غربی'), ('تودلی شمالی', 'تودلی شمالی'), ('تودلی شرقی', 'تودلی شرقی'), ('تودلی جنوبی', 'تودلی جنوبی'), ('تودلی غربی', 'تودلی غربی')], max_length=50, verbose_name='موقعیت'),
        ),
        migrations.AlterField(
            model_name='maqaze',
            name='post_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='maqaze',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='maqaze',
            name='sanad',
            field=models.CharField(choices=[('سند تک برگ', 'سند تک برگ'), ('سند قدیمی', 'سند قدیمی'), ('سند شاعی', 'سند شاعی'), ('فاقد سند', 'فاقد سند')], max_length=50, verbose_name='سند'),
        ),
        migrations.AlterField(
            model_name='maqaze',
            name='sarqofli',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='سرقفلی'),
        ),
        migrations.AlterField(
            model_name='maqaze',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='maqaze',
            name='topography',
            field=models.CharField(choices=[('شیب دار', 'شیب دار'), ('تپه ماهور', 'تپه ماهور'), ('مسطح', 'مسطح')], max_length=50, verbose_name='توپوگرافی'),
        ),
        migrations.AlterField(
            model_name='maqaze',
            name='view',
            field=models.CharField(choices=[('عالی', 'عالی'), ('خوب', 'خوب'), ('متوسط', 'متوسط'), ('بد', 'بد')], max_length=50, verbose_name='چشم انداز'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='address',
            field=models.TextField(null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مساحت'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='area_building',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='متراژ'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='asansor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='آسانسور'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='baft',
            field=models.CharField(choices=[('شهری', 'شهری'), ('روستایی', 'روستایی'), ('خارج بافت', 'خارج بافت'), ('قسمتی در بافت', 'قسمتی در بافت'), ('قابلیت الحاق به بافت', 'قابلیت الحاق به بافت')], max_length=50, verbose_name='بافت'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='bam',
            field=models.CharField(choices=[('اسپانش', 'اسپانش'), ('شیروانی', 'شیروانی'), ('مسطح سنتی', 'مسطح سنتی')], max_length=50, verbose_name='بام'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='bar_zamin',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='بر زمین'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='build_age',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='سال ساخت'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='dastrsi',
            field=models.CharField(choices=[('آسفالت', 'آسفالت'), ('خاکی', 'خاکی'), ('خاکی قدیمی', 'خاکی قدیمی'), ('عدم دسترسی', 'عدم دسترسی'), ('سایر موارد', 'سایر موارد')], max_length=50, verbose_name='دسترسی'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='description',
            field=models.TextField(null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='edit',
            field=models.CharField(choices=[('دارد', 'دارد'), ('ندارد', 'ندارد')], max_length=50, verbose_name='وضعیت اصلاحی'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='features',
            field=models.CharField(choices=[('مشجر', 'مشجر'), ('درخشان مشجر', 'درخشان مشجر'), ('فضا سازی شده', 'فضا سازی شده'), ('فاقد ویژگی خاص', 'فاقد ویژگی خاص')], max_length=50, verbose_name='ویژگی ها'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='floor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='طبقه'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='floor_count',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='تعدا طبقات'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='garmayesh',
            field=models.CharField(choices=[('بخاری', 'بخاری'), ('موتور خانه', 'موتور خانه'), ('فن گویل', 'فن کوِیل'), ('چیلر', 'چیلر')], max_length=50, verbose_name='گرمایش'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='gozar',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='گذر'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='image_10',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='image_6',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='image_7',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='image_8',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='image_9',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='javaz',
            field=models.CharField(choices=[('دارد', 'دارد'), ('ندارد', 'ندارد'), ('مراحل اداری اخذ جواز', 'مراحل اداری اخذ جواز')], max_length=50, verbose_name='جواز'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='javaz_villa',
            field=models.CharField(choices=[('نقشه؟', 'نقشه؟'), ('عدم', 'عدم'), ('پایان کار', 'پایان کار')], max_length=50, verbose_name='وضعیت جواز'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='kaf',
            field=models.CharField(choices=[('سنگ', 'سنگ'), ('سرامیک', 'سرامیک'), ('سایر', 'سایر')], max_length=50, verbose_name='کف'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='karbari',
            field=models.CharField(choices=[('مسکونی', 'مسکونی'), ('صنعتی', 'صنعتی'), ('تجاری', 'تجاری'), ('کشاورزی', 'کشاورزی'), ('اداری', 'اداری'), ('سایر', 'سایر')], max_length=50, verbose_name='کاربری'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='kichen',
            field=models.CharField(choices=[('اپن', 'اپن'), ('زیر اپن', 'زیر اپن'), ('کلوز', 'کلوز')], max_length=50, verbose_name='آشپزخانه'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='malek_address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس مالک'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='malek_mobile',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='تلفن مالک'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='malek_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام مالک'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='malek_need',
            field=models.CharField(choices=[('فروش', 'فروش'), ('تهاتر', 'تهاتر'), ('مشارکت', 'مشارکت'), ('معاوضه', 'معاوضه')], max_length=50, verbose_name='نیاز مالک'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='mechanic_biulding',
            field=models.CharField(choices=[('ستون ها', 'ستون ها'), ('رازر ها', 'رازر ها'), ('سایر', 'سایر')], max_length=50, verbose_name='مکانیک ساختمان'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='nama_building',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نمای ساختمان'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='necessary_mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن ضروری'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='num_malek',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='تعداد مالک'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='others',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='سایر موارد'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='parking',
            field=models.CharField(choices=[('مسقف', 'مسقف'), ('فضا باز', 'فضا باز'), ('ندارد', 'ندارد')], max_length=50, verbose_name='پارکینگ'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='position',
            field=models.CharField(choices=[('شمالی', 'شمالی'), ('شرقی', 'شرقی'), ('جنوبی', 'جنوبی'), ('غربی', 'غربی'), ('تودلی شمالی', 'تودلی شمالی'), ('تودلی شرقی', 'تودلی شرقی'), ('تودلی جنوبی', 'تودلی جنوبی'), ('تودلی غربی', 'تودلی غربی')], max_length=50, verbose_name='موقعیت'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='post_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='sanad',
            field=models.CharField(choices=[('سند تک برگ', 'سند تک برگ'), ('سند قدیمی', 'سند قدیمی'), ('سند شاعی', 'سند شاعی'), ('فاقد سند', 'فاقد سند')], max_length=50, verbose_name='سند'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='sarmayesh',
            field=models.CharField(choices=[('کولر آبی', 'کولر آبی'), ('کولر گازی', 'کولر گازی'), ('فن کویل', 'فن کویل')], max_length=50, verbose_name='سرمایش'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='system_garmayesh',
            field=models.CharField(choices=[('از کف', 'از کف'), ('بخاری', 'بخاری'), ('رادیاتور', 'رادیاتور'), ('شومینه', 'شومینه')], max_length=50, verbose_name='سیستم گرمایش'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='topography',
            field=models.CharField(choices=[('شیب دار', 'شیب دار'), ('تپه ماهور', 'تپه ماهور'), ('مسطح', 'مسطح')], max_length=50, verbose_name='توپوگرافی'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='type_building',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع ساخت'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='varase',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ورثه'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='view',
            field=models.CharField(choices=[('عالی', 'عالی'), ('خوب', 'خوب'), ('متوسط', 'متوسط'), ('بد', 'بد')], max_length=50, verbose_name='چشم انداز'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='zelzele',
            field=models.CharField(choices=[('عالی', 'عالی'), ('خوب', 'خوب'), ('متوسط', 'متوسط'), ('بد', 'بد')], max_length=50, verbose_name='طراحی ضد زلزله'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='address',
            field=models.TextField(null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مساحت'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='area_building',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='متراژ بنا'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='baft',
            field=models.CharField(choices=[('شهری', 'شهری'), ('روستایی', 'روستایی'), ('خارج بافت', 'خارج بافت'), ('قسمتی در بافت', 'قسمتی در بافت'), ('قابلیت الحاق به بافت', 'قابلیت الحاق به بافت')], max_length=50, verbose_name='بافت'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='bam',
            field=models.CharField(choices=[('اسپانش', 'اسپانش'), ('شیروانی', 'شیروانی'), ('مسطح سنتی', 'مسطح سنتی')], max_length=50, verbose_name='بام'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='bar_zamin',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='بر زمین'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='build_age',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='سال ساخت'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='dastrsi',
            field=models.CharField(choices=[('آسفالت', 'آسفالت'), ('خاکی', 'خاکی'), ('خاکی قدیمی', 'خاکی قدیمی'), ('عدم دسترسی', 'عدم دسترسی'), ('سایر موارد', 'سایر موارد')], max_length=50, verbose_name='دسترسی'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='description',
            field=models.TextField(null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='edit',
            field=models.CharField(choices=[('دارد', 'دارد'), ('ندارد', 'ندارد')], max_length=50, verbose_name='وضعیت اصلاحی'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='features',
            field=models.CharField(choices=[('مشجر', 'مشجر'), ('درخشان مشجر', 'درخشان مشجر'), ('فضا سازی شده', 'فضا سازی شده'), ('فاقد ویژگی خاص', 'فاقد ویژگی خاص')], max_length=50, verbose_name='ویژگی ها'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='fitures',
            field=models.CharField(choices=[('سونا', 'سونا'), ('استخر سرپوشیده', 'استخر سر پوشیده'), ('استخر باز', 'استخر باز')], max_length=50, verbose_name='سایر ویژگی های خاص'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='floor_count',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='تعداد طبقات'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='garmayesh',
            field=models.CharField(choices=[('بخاری', 'بخاری'), ('موتور خانه', 'موتور خانه'), ('فن گویل', 'فن کوِیل'), ('چیلر', 'چیلر')], max_length=50, verbose_name='گرمایش'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='gozar',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='گذر'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='image_10',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='image_6',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='image_7',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='image_8',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='image_9',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='javaz',
            field=models.CharField(choices=[('دارد', 'دارد'), ('ندارد', 'ندارد'), ('مراحل اداری اخذ جواز', 'مراحل اداری اخذ جواز')], max_length=50, verbose_name='جواز'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='javaz_villa',
            field=models.CharField(choices=[('نقشه؟', 'نقشه؟'), ('عدم', 'عدم'), ('پایان کار', 'پایان کار')], max_length=50, verbose_name='جواز ویلا'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='kaf',
            field=models.CharField(choices=[('سنگ', 'سنگ'), ('سرامیک', 'سرامیک'), ('سایر', 'سایر')], max_length=50, verbose_name='کف'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='karbari',
            field=models.CharField(choices=[('مسکونی', 'مسکونی'), ('صنعتی', 'صنعتی'), ('تجاری', 'تجاری'), ('کشاورزی', 'کشاورزی'), ('اداری', 'اداری'), ('سایر', 'سایر')], max_length=50, verbose_name='کاربری'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='kichen',
            field=models.CharField(choices=[('اپن', 'اپن'), ('زیر اپن', 'زیر اپن'), ('کلوز', 'کلوز')], max_length=50, verbose_name='آشپزخانه'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='malek_address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس مالک'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='malek_mobile',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='تلفن مالک'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='malek_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام مالک'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='malek_need',
            field=models.CharField(choices=[('فروش', 'فروش'), ('تهاتر', 'تهاتر'), ('مشارکت', 'مشارکت'), ('معاوضه', 'معاوضه')], max_length=50, verbose_name='نیاز مالک'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='mechanic_biulding',
            field=models.CharField(choices=[('ستون ها', 'ستون ها'), ('رازر ها', 'رازر ها'), ('سایر', 'سایر')], max_length=50, verbose_name='مکانیک ساختمان'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='nama_building',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نمای ساختمان'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='necessary_mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن ضروری'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='parking',
            field=models.CharField(choices=[('مسقف', 'مسقف'), ('فضا باز', 'فضا باز'), ('ندارد', 'ندارد')], max_length=50, verbose_name='پارکینگ'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='position',
            field=models.CharField(choices=[('شمالی', 'شمالی'), ('شرقی', 'شرقی'), ('جنوبی', 'جنوبی'), ('غربی', 'غربی'), ('تودلی شمالی', 'تودلی شمالی'), ('تودلی شرقی', 'تودلی شرقی'), ('تودلی جنوبی', 'تودلی جنوبی'), ('تودلی غربی', 'تودلی غربی')], max_length=50, verbose_name='موقعیت'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='post_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='sanad',
            field=models.CharField(choices=[('سند تک برگ', 'سند تک برگ'), ('سند قدیمی', 'سند قدیمی'), ('سند شاعی', 'سند شاعی'), ('فاقد سند', 'فاقد سند')], max_length=50, verbose_name='سند'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='sarmayesh',
            field=models.CharField(choices=[('کولر آبی', 'کولر آبی'), ('کولر گازی', 'کولر گازی'), ('فن کویل', 'فن کویل')], max_length=50, verbose_name='سرمایش'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='system_garmayesh',
            field=models.CharField(choices=[('از کف', 'از کف'), ('بخاری', 'بخاری'), ('رادیاتور', 'رادیاتور'), ('شومینه', 'شومینه')], max_length=50, verbose_name='سیستم گرمایش'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='topography',
            field=models.CharField(choices=[('شیب دار', 'شیب دار'), ('تپه ماهور', 'تپه ماهور'), ('مسطح', 'مسطح')], max_length=50, verbose_name='توپوگرافی'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='type_building',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع ساخت'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='view',
            field=models.CharField(choices=[('عالی', 'عالی'), ('خوب', 'خوب'), ('متوسط', 'متوسط'), ('بد', 'بد')], max_length=50, verbose_name='چشم انداز'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='zelzele',
            field=models.CharField(choices=[('عالی', 'عالی'), ('خوب', 'خوب'), ('متوسط', 'متوسط'), ('بد', 'بد')], max_length=50, verbose_name='طراحی ضد زلزله '),
        ),
        migrations.AlterField(
            model_name='zamin',
            name='address',
            field=models.TextField(null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='zamin',
            name='area',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مساحت'),
        ),
        migrations.AlterField(
            model_name='zamin',
            name='baft',
            field=models.CharField(choices=[('شهری', 'شهری'), ('روستایی', 'روستایی'), ('خارج بافت', 'خارج بافت'), ('قسمتی در بافت', 'قسمتی در بافت'), ('قابلیت الحاق به بافت', 'قابلیت الحاق به بافت')], max_length=50, verbose_name='بافت'),
        ),
        migrations.AlterField(
            model_name='zamin',
            name='bar_zamin',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='بر زمین'),
        ),
        migrations.AlterField(
            model_name='zamin',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='zamin',
            name='dastrsi',
            field=models.CharField(choices=[('آسفالت', 'آسفالت'), ('خاکی', 'خاکی'), ('خاکی قدیمی', 'خاکی قدیمی'), ('عدم دسترسی', 'عدم دسترسی'), ('سایر موارد', 'سایر موارد')], max_length=50, verbose_name='دسترسی'),
        ),
        migrations.AlterField(
            model_name='zamin',
            name='description',
            field=models.TextField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='zamin',
            name='edit',
            field=models.CharField(choices=[('دارد', 'دارد'), ('ندارد', 'ندارد')], max_length=50, verbose_name='وضعیت اصلاحی'),
        ),
        migrations.AlterField(
            model_name='zamin',
            name='features',
            field=models.CharField(choices=[('مشجر', 'مشجر'), ('درخشان مشجر', 'درخشان مشجر'), ('فضا سازی شده', 'فضا سازی شده'), ('فاقد ویژگی خاص', 'فاقد ویژگی خاص')], max_length=50, verbose_name='ویژگی ها'),
        ),
        migrations.AlterField(
            model_name='zamin',
            name='gozar',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='گذر'),
        ),
        migrations.AlterField(
            model_name='zamin',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='zamin',
            name='image_10',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='zamin',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='zamin',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='zamin',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='zamin',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='zamin',
            name='image_6',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='zamin',
            name='image_7',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='zamin',
            name='image_8',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='zamin',
            name='image_9',
            field=models.ImageField(blank=True, null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='zamin',
            name='javaz',
            field=models.CharField(choices=[('دارد', 'دارد'), ('ندارد', 'ندارد'), ('مراحل اداری اخذ جواز', 'مراحل اداری اخذ جواز')], max_length=50, verbose_name='جواز'),
        ),
        migrations.AlterField(
            model_name='zamin',
            name='karbari',
            field=models.CharField(choices=[('مسکونی', 'مسکونی'), ('صنعتی', 'صنعتی'), ('تجاری', 'تجاری'), ('کشاورزی', 'کشاورزی'), ('اداری', 'اداری'), ('سایر', 'سایر')], max_length=50, verbose_name='کاربری'),
        ),
        migrations.AlterField(
            model_name='zamin',
            name='malek_address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس مالک'),
        ),
        migrations.AlterField(
            model_name='zamin',
            name='malek_mobile',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='تلفن مالک'),
        ),
        migrations.AlterField(
            model_name='zamin',
            name='malek_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام مالک'),
        ),
        migrations.AlterField(
            model_name='zamin',
            name='malek_need',
            field=models.CharField(choices=[('فروش', 'فروش'), ('تهاتر', 'تهاتر'), ('مشارکت', 'مشارکت'), ('معاوضه', 'معاوضه')], max_length=50, verbose_name='نیاز مالک'),
        ),
        migrations.AlterField(
            model_name='zamin',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='zamin',
            name='necessary_mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن ضروری'),
        ),
        migrations.AlterField(
            model_name='zamin',
            name='position',
            field=models.CharField(choices=[('شمالی', 'شمالی'), ('شرقی', 'شرقی'), ('جنوبی', 'جنوبی'), ('غربی', 'غربی'), ('تودلی شمالی', 'تودلی شمالی'), ('تودلی شرقی', 'تودلی شرقی'), ('تودلی جنوبی', 'تودلی جنوبی'), ('تودلی غربی', 'تودلی غربی')], max_length=50, verbose_name='موقعیت'),
        ),
        migrations.AlterField(
            model_name='zamin',
            name='post_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='zamin',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='zamin',
            name='sanad',
            field=models.CharField(choices=[('سند تک برگ', 'سند تک برگ'), ('سند قدیمی', 'سند قدیمی'), ('سند شاعی', 'سند شاعی'), ('فاقد سند', 'فاقد سند')], max_length=50, verbose_name='سند'),
        ),
        migrations.AlterField(
            model_name='zamin',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='zamin',
            name='topography',
            field=models.CharField(choices=[('شیب دار', 'شیب دار'), ('تپه ماهور', 'تپه ماهور'), ('مسطح', 'مسطح')], max_length=50, verbose_name='توپوگرافی'),
        ),
        migrations.AlterField(
            model_name='zamin',
            name='view',
            field=models.CharField(choices=[('عالی', 'عالی'), ('خوب', 'خوب'), ('متوسط', 'متوسط'), ('بد', 'بد')], max_length=50, verbose_name='چشم انداز'),
        ),
    ]
