# Generated by Django 4.1.2 on 2022-11-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amlak', '0016_alter_bagh_area_alter_bagh_hagh_ab_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveuser',
            name='description',
            field=models.TextField(null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='archiveuser',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='maqaze',
            name='description',
            field=models.TextField(null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='zamin',
            name='description',
            field=models.TextField(null=True, verbose_name='توضیحات'),
        ),
    ]
