# Generated by Django 4.1.2 on 2022-11-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amlak', '0017_archiveuser_description_archiveuser_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='image_1',
            field=models.ImageField(null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='bagh',
            name='image_1',
            field=models.ImageField(null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='image_1',
            field=models.ImageField(null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='maqaze',
            name='image_1',
            field=models.ImageField(null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='image_1',
            field=models.ImageField(null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='image_1',
            field=models.ImageField(null=True, upload_to='khane', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='zamin',
            name='image_1',
            field=models.ImageField(null=True, upload_to='khane', verbose_name='تصویر'),
        ),
    ]
