# Generated by Django 4.1.2 on 2022-11-08 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amlak', '0018_alter_apartment_image_1_alter_bagh_image_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='malek_address',
        ),
        migrations.RemoveField(
            model_name='bagh',
            name='malek_address',
        ),
        migrations.RemoveField(
            model_name='khane',
            name='malek_address',
        ),
        migrations.RemoveField(
            model_name='maqaze',
            name='malek_address',
        ),
        migrations.RemoveField(
            model_name='mostaghelat',
            name='malek_address',
        ),
        migrations.RemoveField(
            model_name='villa',
            name='malek_address',
        ),
        migrations.RemoveField(
            model_name='zamin',
            name='malek_address',
        ),
    ]
