# Generated by Django 4.1.2 on 2022-11-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amlak', '0019_remove_apartment_malek_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='ensheabat',
            field=models.CharField(choices=[('آب', 'آب'), ('برق', 'برق'), ('گاز', 'گاز'), ('تلفن', 'تلفن')], default=1, max_length=50, verbose_name='انشعابات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bagh',
            name='ensheabat',
            field=models.CharField(choices=[('آب', 'آب'), ('برق', 'برق'), ('گاز', 'گاز'), ('تلفن', 'تلفن')], default=1, max_length=50, verbose_name='انشعابات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='khane',
            name='ensheabat',
            field=models.CharField(choices=[('آب', 'آب'), ('برق', 'برق'), ('گاز', 'گاز'), ('تلفن', 'تلفن')], default=1, max_length=50, verbose_name='انشعابات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maqaze',
            name='ensheabat',
            field=models.CharField(choices=[('آب', 'آب'), ('برق', 'برق'), ('گاز', 'گاز'), ('تلفن', 'تلفن')], default=1, max_length=50, verbose_name='انشعابات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mostaghelat',
            name='ensheabat',
            field=models.CharField(choices=[('آب', 'آب'), ('برق', 'برق'), ('گاز', 'گاز'), ('تلفن', 'تلفن')], default=1, max_length=50, verbose_name='انشعابات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='villa',
            name='ensheabat',
            field=models.CharField(choices=[('آب', 'آب'), ('برق', 'برق'), ('گاز', 'گاز'), ('تلفن', 'تلفن')], default=1, max_length=50, verbose_name='انشعابات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zamin',
            name='ensheabat',
            field=models.CharField(choices=[('آب', 'آب'), ('برق', 'برق'), ('گاز', 'گاز'), ('تلفن', 'تلفن')], default=1, max_length=50, verbose_name='انشعابات'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartment',
            name='bam',
            field=models.CharField(choices=[('اسپانیش', 'اسپانیش'), ('شیروانی', 'شیروانی'), ('مسطح سنتی', 'مسطح سنتی'), ('روف گاردن', 'روف گاردن'), ('سایر موارد', 'سایر موارد')], max_length=50, verbose_name='بام'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='features',
            field=models.CharField(choices=[('مشجر', 'مشجر'), ('درختان مثمر', 'درختان مثمر'), ('فضا سازی شده', 'فضا سازی شده'), ('فاقد ویژگی خاص', 'فاقد ویژگی خاص'), ('سایر موارد', 'سایر موارد')], max_length=50, verbose_name='ویژگی ها'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='fitures',
            field=models.CharField(choices=[('سونا', 'سونا'), ('استخر سرپوشیده', 'استخر سر پوشیده'), ('استخر گرم', 'استخر گرم'), ('استخر سرد', 'استخر سرد')], max_length=50, verbose_name='ویژگی ها'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='garmayesh',
            field=models.CharField(choices=[('خورشیدی', 'خورشیدی'), ('موتور خانه', 'موتور خانه'), ('پکیج', 'پکیج'), ('چیلر', 'چیلر')], max_length=50, verbose_name='گرمایش'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='javaz_villa',
            field=models.CharField(choices=[('دفترچه ساخت', 'دفترچه ساخت'), ('عدم خلاف', 'عدم خلاف'), ('پایان کار', 'پایان کار')], max_length=50, verbose_name='جواز ویلا'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='kichen',
            field=models.CharField(choices=[('اپن', 'اپن'), ('نیمه اپن', 'نیمه اپن'), ('کلوز', 'کلوز')], max_length=50, verbose_name='آشپزخانه'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='mechanic_biulding',
            field=models.CharField(choices=[('فلزی', 'فلزی'), ('بتنی', 'بتنی'), ('نیمه اسکلت', 'نیمه اسکلت'), ('سایر', 'سایر')], max_length=50, verbose_name='مکانیک ساختمان'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='position',
            field=models.CharField(choices=[('شمالی', 'شمالی'), ('شرقی', 'شرقی'), ('جنوبی', 'جنوبی'), ('غربی', 'غربی'), ('تودلی شمالی', 'تودلی شمالی'), ('تودلی شرقی', 'تودلی شرقی'), ('تودلی جنوبی', 'تودلی جنوبی'), ('تودلی غربی', 'تودلی غربی'), ('دو کله', 'دو کله'), ('سه بر', 'سه بر'), ('دوبر', 'دوبر'), ('جزیره ای', 'جزیره ای')], max_length=50, verbose_name='موقعیت'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='sanad',
            field=models.CharField(choices=[('سند تک برگ', 'سند تک برگ'), ('سند قدیمی', 'سند قدیمی'), ('سند مشاعی', 'سند مشاعی'), ('مبایعه نامه', 'مبایعه نامه'), ('سایر', 'سایر')], max_length=50, verbose_name='سند'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='system_garmayesh',
            field=models.CharField(choices=[('از کف', 'از کف'), ('بخاری', 'بخاری'), ('رادیاتور', 'رادیاتور'), ('شومینه', 'شومینه'), ('فن کویل', 'فن کوِیل')], max_length=50, verbose_name='سیستم گرمایش'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='topography',
            field=models.CharField(choices=[('شیب دار', 'شیب دار'), ('تپه ماهور', 'تپه ماهور'), ('مسطح', 'مسطح'), ('سایر', 'سایر')], max_length=50, verbose_name='توپوگرافی'),
        ),
        migrations.AlterField(
            model_name='bagh',
            name='features',
            field=models.CharField(choices=[('مشجر', 'مشجر'), ('درختان مثمر', 'درختان مثمر'), ('فضا سازی شده', 'فضا سازی شده'), ('فاقد ویژگی خاص', 'فاقد ویژگی خاص'), ('سایر موارد', 'سایر موارد')], max_length=50, verbose_name='ویژگی ها'),
        ),
        migrations.AlterField(
            model_name='bagh',
            name='position',
            field=models.CharField(choices=[('شمالی', 'شمالی'), ('شرقی', 'شرقی'), ('جنوبی', 'جنوبی'), ('غربی', 'غربی'), ('تودلی شمالی', 'تودلی شمالی'), ('تودلی شرقی', 'تودلی شرقی'), ('تودلی جنوبی', 'تودلی جنوبی'), ('تودلی غربی', 'تودلی غربی'), ('دو کله', 'دو کله'), ('سه بر', 'سه بر'), ('دوبر', 'دوبر'), ('جزیره ای', 'جزیره ای')], max_length=50, verbose_name='موقعیت'),
        ),
        migrations.AlterField(
            model_name='bagh',
            name='sanad',
            field=models.CharField(choices=[('سند تک برگ', 'سند تک برگ'), ('سند قدیمی', 'سند قدیمی'), ('سند مشاعی', 'سند مشاعی'), ('مبایعه نامه', 'مبایعه نامه'), ('سایر', 'سایر')], max_length=50, verbose_name='سند'),
        ),
        migrations.AlterField(
            model_name='bagh',
            name='topography',
            field=models.CharField(choices=[('شیب دار', 'شیب دار'), ('تپه ماهور', 'تپه ماهور'), ('مسطح', 'مسطح'), ('سایر', 'سایر')], max_length=50, verbose_name='توپوگرافی'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='bam',
            field=models.CharField(choices=[('اسپانیش', 'اسپانیش'), ('شیروانی', 'شیروانی'), ('مسطح سنتی', 'مسطح سنتی'), ('روف گاردن', 'روف گاردن'), ('سایر موارد', 'سایر موارد')], max_length=50, verbose_name='بام'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='features',
            field=models.CharField(choices=[('مشجر', 'مشجر'), ('درختان مثمر', 'درختان مثمر'), ('فضا سازی شده', 'فضا سازی شده'), ('فاقد ویژگی خاص', 'فاقد ویژگی خاص'), ('سایر موارد', 'سایر موارد')], max_length=50, verbose_name='ویژگی ها'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='fitures',
            field=models.CharField(choices=[('سونا', 'سونا'), ('استخر سرپوشیده', 'استخر سر پوشیده'), ('استخر گرم', 'استخر گرم'), ('استخر سرد', 'استخر سرد')], max_length=50, verbose_name='سایر ویژگی های خاص'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='garmayesh',
            field=models.CharField(choices=[('خورشیدی', 'خورشیدی'), ('موتور خانه', 'موتور خانه'), ('پکیج', 'پکیج'), ('چیلر', 'چیلر')], max_length=50, verbose_name='گرمایش'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='javaz_villa',
            field=models.CharField(choices=[('دفترچه ساخت', 'دفترچه ساخت'), ('عدم خلاف', 'عدم خلاف'), ('پایان کار', 'پایان کار')], max_length=50, verbose_name='وضعیت جواز'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='kichen',
            field=models.CharField(choices=[('اپن', 'اپن'), ('نیمه اپن', 'نیمه اپن'), ('کلوز', 'کلوز')], max_length=50, verbose_name='آشپزخانه'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='mechanic_biulding',
            field=models.CharField(choices=[('فلزی', 'فلزی'), ('بتنی', 'بتنی'), ('نیمه اسکلت', 'نیمه اسکلت'), ('سایر', 'سایر')], max_length=50, verbose_name='مکانیک ساختمان'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='position',
            field=models.CharField(choices=[('شمالی', 'شمالی'), ('شرقی', 'شرقی'), ('جنوبی', 'جنوبی'), ('غربی', 'غربی'), ('تودلی شمالی', 'تودلی شمالی'), ('تودلی شرقی', 'تودلی شرقی'), ('تودلی جنوبی', 'تودلی جنوبی'), ('تودلی غربی', 'تودلی غربی'), ('دو کله', 'دو کله'), ('سه بر', 'سه بر'), ('دوبر', 'دوبر'), ('جزیره ای', 'جزیره ای')], max_length=50, verbose_name='موقعیت'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='sanad',
            field=models.CharField(choices=[('سند تک برگ', 'سند تک برگ'), ('سند قدیمی', 'سند قدیمی'), ('سند مشاعی', 'سند مشاعی'), ('مبایعه نامه', 'مبایعه نامه'), ('سایر', 'سایر')], max_length=50, verbose_name='سند'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='system_garmayesh',
            field=models.CharField(choices=[('از کف', 'از کف'), ('بخاری', 'بخاری'), ('رادیاتور', 'رادیاتور'), ('شومینه', 'شومینه'), ('فن کویل', 'فن کوِیل')], max_length=50, verbose_name='سیستم گرمایش'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='topography',
            field=models.CharField(choices=[('شیب دار', 'شیب دار'), ('تپه ماهور', 'تپه ماهور'), ('مسطح', 'مسطح'), ('سایر', 'سایر')], max_length=50, verbose_name='توپوگرافی'),
        ),
        migrations.AlterField(
            model_name='maqaze',
            name='features',
            field=models.CharField(choices=[('مشجر', 'مشجر'), ('درختان مثمر', 'درختان مثمر'), ('فضا سازی شده', 'فضا سازی شده'), ('فاقد ویژگی خاص', 'فاقد ویژگی خاص'), ('سایر موارد', 'سایر موارد')], max_length=50, verbose_name='ویژگی ها'),
        ),
        migrations.AlterField(
            model_name='maqaze',
            name='position',
            field=models.CharField(choices=[('شمالی', 'شمالی'), ('شرقی', 'شرقی'), ('جنوبی', 'جنوبی'), ('غربی', 'غربی'), ('تودلی شمالی', 'تودلی شمالی'), ('تودلی شرقی', 'تودلی شرقی'), ('تودلی جنوبی', 'تودلی جنوبی'), ('تودلی غربی', 'تودلی غربی'), ('دو کله', 'دو کله'), ('سه بر', 'سه بر'), ('دوبر', 'دوبر'), ('جزیره ای', 'جزیره ای')], max_length=50, verbose_name='موقعیت'),
        ),
        migrations.AlterField(
            model_name='maqaze',
            name='sanad',
            field=models.CharField(choices=[('سند تک برگ', 'سند تک برگ'), ('سند قدیمی', 'سند قدیمی'), ('سند مشاعی', 'سند مشاعی'), ('مبایعه نامه', 'مبایعه نامه'), ('سایر', 'سایر')], max_length=50, verbose_name='سند'),
        ),
        migrations.AlterField(
            model_name='maqaze',
            name='topography',
            field=models.CharField(choices=[('شیب دار', 'شیب دار'), ('تپه ماهور', 'تپه ماهور'), ('مسطح', 'مسطح'), ('سایر', 'سایر')], max_length=50, verbose_name='توپوگرافی'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='bam',
            field=models.CharField(choices=[('اسپانیش', 'اسپانیش'), ('شیروانی', 'شیروانی'), ('مسطح سنتی', 'مسطح سنتی'), ('روف گاردن', 'روف گاردن'), ('سایر موارد', 'سایر موارد')], max_length=50, verbose_name='بام'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='features',
            field=models.CharField(choices=[('مشجر', 'مشجر'), ('درختان مثمر', 'درختان مثمر'), ('فضا سازی شده', 'فضا سازی شده'), ('فاقد ویژگی خاص', 'فاقد ویژگی خاص'), ('سایر موارد', 'سایر موارد')], max_length=50, verbose_name='ویژگی ها'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='garmayesh',
            field=models.CharField(choices=[('خورشیدی', 'خورشیدی'), ('موتور خانه', 'موتور خانه'), ('پکیج', 'پکیج'), ('چیلر', 'چیلر')], max_length=50, verbose_name='گرمایش'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='javaz_villa',
            field=models.CharField(choices=[('دفترچه ساخت', 'دفترچه ساخت'), ('عدم خلاف', 'عدم خلاف'), ('پایان کار', 'پایان کار')], max_length=50, verbose_name='وضعیت جواز'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='kichen',
            field=models.CharField(choices=[('اپن', 'اپن'), ('نیمه اپن', 'نیمه اپن'), ('کلوز', 'کلوز')], max_length=50, verbose_name='آشپزخانه'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='mechanic_biulding',
            field=models.CharField(choices=[('فلزی', 'فلزی'), ('بتنی', 'بتنی'), ('نیمه اسکلت', 'نیمه اسکلت'), ('سایر', 'سایر')], max_length=50, verbose_name='مکانیک ساختمان'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='position',
            field=models.CharField(choices=[('شمالی', 'شمالی'), ('شرقی', 'شرقی'), ('جنوبی', 'جنوبی'), ('غربی', 'غربی'), ('تودلی شمالی', 'تودلی شمالی'), ('تودلی شرقی', 'تودلی شرقی'), ('تودلی جنوبی', 'تودلی جنوبی'), ('تودلی غربی', 'تودلی غربی'), ('دو کله', 'دو کله'), ('سه بر', 'سه بر'), ('دوبر', 'دوبر'), ('جزیره ای', 'جزیره ای')], max_length=50, verbose_name='موقعیت'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='sanad',
            field=models.CharField(choices=[('سند تک برگ', 'سند تک برگ'), ('سند قدیمی', 'سند قدیمی'), ('سند مشاعی', 'سند مشاعی'), ('مبایعه نامه', 'مبایعه نامه'), ('سایر', 'سایر')], max_length=50, verbose_name='سند'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='system_garmayesh',
            field=models.CharField(choices=[('از کف', 'از کف'), ('بخاری', 'بخاری'), ('رادیاتور', 'رادیاتور'), ('شومینه', 'شومینه'), ('فن کویل', 'فن کوِیل')], max_length=50, verbose_name='سیستم گرمایش'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='topography',
            field=models.CharField(choices=[('شیب دار', 'شیب دار'), ('تپه ماهور', 'تپه ماهور'), ('مسطح', 'مسطح'), ('سایر', 'سایر')], max_length=50, verbose_name='توپوگرافی'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='bam',
            field=models.CharField(choices=[('اسپانیش', 'اسپانیش'), ('شیروانی', 'شیروانی'), ('مسطح سنتی', 'مسطح سنتی'), ('روف گاردن', 'روف گاردن'), ('سایر موارد', 'سایر موارد')], max_length=50, verbose_name='بام'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='features',
            field=models.CharField(choices=[('مشجر', 'مشجر'), ('درختان مثمر', 'درختان مثمر'), ('فضا سازی شده', 'فضا سازی شده'), ('فاقد ویژگی خاص', 'فاقد ویژگی خاص'), ('سایر موارد', 'سایر موارد')], max_length=50, verbose_name='ویژگی ها'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='fitures',
            field=models.CharField(choices=[('سونا', 'سونا'), ('استخر سرپوشیده', 'استخر سر پوشیده'), ('استخر گرم', 'استخر گرم'), ('استخر سرد', 'استخر سرد')], max_length=50, verbose_name='سایر ویژگی های خاص'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='garmayesh',
            field=models.CharField(choices=[('خورشیدی', 'خورشیدی'), ('موتور خانه', 'موتور خانه'), ('پکیج', 'پکیج'), ('چیلر', 'چیلر')], max_length=50, verbose_name='گرمایش'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='javaz_villa',
            field=models.CharField(choices=[('دفترچه ساخت', 'دفترچه ساخت'), ('عدم خلاف', 'عدم خلاف'), ('پایان کار', 'پایان کار')], max_length=50, verbose_name='جواز ویلا'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='kichen',
            field=models.CharField(choices=[('اپن', 'اپن'), ('نیمه اپن', 'نیمه اپن'), ('کلوز', 'کلوز')], max_length=50, verbose_name='آشپزخانه'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='mechanic_biulding',
            field=models.CharField(choices=[('فلزی', 'فلزی'), ('بتنی', 'بتنی'), ('نیمه اسکلت', 'نیمه اسکلت'), ('سایر', 'سایر')], max_length=50, verbose_name='مکانیک ساختمان'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='position',
            field=models.CharField(choices=[('شمالی', 'شمالی'), ('شرقی', 'شرقی'), ('جنوبی', 'جنوبی'), ('غربی', 'غربی'), ('تودلی شمالی', 'تودلی شمالی'), ('تودلی شرقی', 'تودلی شرقی'), ('تودلی جنوبی', 'تودلی جنوبی'), ('تودلی غربی', 'تودلی غربی'), ('دو کله', 'دو کله'), ('سه بر', 'سه بر'), ('دوبر', 'دوبر'), ('جزیره ای', 'جزیره ای')], max_length=50, verbose_name='موقعیت'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='sanad',
            field=models.CharField(choices=[('سند تک برگ', 'سند تک برگ'), ('سند قدیمی', 'سند قدیمی'), ('سند مشاعی', 'سند مشاعی'), ('مبایعه نامه', 'مبایعه نامه'), ('سایر', 'سایر')], max_length=50, verbose_name='سند'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='system_garmayesh',
            field=models.CharField(choices=[('از کف', 'از کف'), ('بخاری', 'بخاری'), ('رادیاتور', 'رادیاتور'), ('شومینه', 'شومینه'), ('فن کویل', 'فن کوِیل')], max_length=50, verbose_name='سیستم گرمایش'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='topography',
            field=models.CharField(choices=[('شیب دار', 'شیب دار'), ('تپه ماهور', 'تپه ماهور'), ('مسطح', 'مسطح'), ('سایر', 'سایر')], max_length=50, verbose_name='توپوگرافی'),
        ),
        migrations.AlterField(
            model_name='zamin',
            name='features',
            field=models.CharField(choices=[('مشجر', 'مشجر'), ('درختان مثمر', 'درختان مثمر'), ('فضا سازی شده', 'فضا سازی شده'), ('فاقد ویژگی خاص', 'فاقد ویژگی خاص'), ('سایر موارد', 'سایر موارد')], max_length=50, verbose_name='ویژگی ها'),
        ),
        migrations.AlterField(
            model_name='zamin',
            name='position',
            field=models.CharField(choices=[('شمالی', 'شمالی'), ('شرقی', 'شرقی'), ('جنوبی', 'جنوبی'), ('غربی', 'غربی'), ('تودلی شمالی', 'تودلی شمالی'), ('تودلی شرقی', 'تودلی شرقی'), ('تودلی جنوبی', 'تودلی جنوبی'), ('تودلی غربی', 'تودلی غربی'), ('دو کله', 'دو کله'), ('سه بر', 'سه بر'), ('دوبر', 'دوبر'), ('جزیره ای', 'جزیره ای')], max_length=50, verbose_name='موقعیت'),
        ),
        migrations.AlterField(
            model_name='zamin',
            name='sanad',
            field=models.CharField(choices=[('سند تک برگ', 'سند تک برگ'), ('سند قدیمی', 'سند قدیمی'), ('سند مشاعی', 'سند مشاعی'), ('مبایعه نامه', 'مبایعه نامه'), ('سایر', 'سایر')], max_length=50, verbose_name='سند'),
        ),
        migrations.AlterField(
            model_name='zamin',
            name='topography',
            field=models.CharField(choices=[('شیب دار', 'شیب دار'), ('تپه ماهور', 'تپه ماهور'), ('مسطح', 'مسطح'), ('سایر', 'سایر')], max_length=50, verbose_name='توپوگرافی'),
        ),
    ]
