# Generated by Django 4.1.2 on 2022-11-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amlak', '0020_apartment_ensheabat_bagh_ensheabat_khane_ensheabat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='javaz_villa',
        ),
        migrations.AddField(
            model_name='bagh',
            name='derakht',
            field=models.CharField(choices=[('مثمر', 'مثمر'), ('سایر', 'سایر')], default=1, max_length=50, verbose_name='نوع درخت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='villa',
            name='amniat',
            field=models.CharField(choices=[('فلزی', 'فلزی'), ('بتنی', 'بتنی'), ('نیمه اسکلت', 'نیمه اسکلت'), ('سایر', 'سایر')], default=1, max_length=50, verbose_name='سیستم امنیت'),
            preserve_default=False,
        ),
    ]
