# Generated by Django 4.1.2 on 2022-11-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amlak', '0022_remove_archiveuser_address_malek_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='ensheabat',
            field=models.CharField(max_length=100, verbose_name='انشعابات'),
        ),
        migrations.AlterField(
            model_name='bagh',
            name='ensheabat',
            field=models.CharField(max_length=100, verbose_name='انشعابات'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='ensheabat',
            field=models.CharField(max_length=100, verbose_name='انشعابات'),
        ),
        migrations.AlterField(
            model_name='maqaze',
            name='ensheabat',
            field=models.CharField(max_length=100, verbose_name='انشعابات'),
        ),
        migrations.AlterField(
            model_name='mostaghelat',
            name='ensheabat',
            field=models.CharField(max_length=100, verbose_name='انشعابات'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='ensheabat',
            field=models.CharField(max_length=100, verbose_name='انشعابات'),
        ),
        migrations.AlterField(
            model_name='zamin',
            name='ensheabat',
            field=models.CharField(max_length=100, verbose_name='انشعابات'),
        ),
    ]
