# Generated by Django 4.1.2 on 2022-11-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amlak', '0023_alter_apartment_ensheabat_alter_bagh_ensheabat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='fitures',
            field=models.CharField(max_length=100, verbose_name='ویژگی ها'),
        ),
        migrations.AlterField(
            model_name='khane',
            name='fitures',
            field=models.CharField(max_length=100, verbose_name='سایر ویژگی های خاص'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='amniat',
            field=models.CharField(choices=[('دوربین', 'دوربین'), ('دزدگیر', 'دزدگیر'), ('حفاظ', 'حفاظ'), ('سایر', 'سایر')], max_length=50, verbose_name='سیستم امنیت'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='fitures',
            field=models.CharField(max_length=100, verbose_name='سایر ویژگی های خاص'),
        ),
    ]
